- name: create deployment config
  k8s_extensions_v1beta1_deployment:
   name: http-source
   namespace: '{{ namespace }}'
   labels:
     app: event-gateway
     service: http-source
   replicas: 1
   spec_template_metadata_labels:
     app: event-gateway
     service: http-source
   containers:
   - env:
     image: docker.io/streamzi/gw-http-source:latest # replace with your application image
     name: http-source
     ports:
     - container_port: 8081
       protocol: TCP

- name: create http-source service
  k8s_v1_service:
   name: http-source
   namespace: '{{ namespace }}'
   labels:
     app: event-gateway
     service: http-source
   selector:
     app: event-gateway
     service: http-source
   ports:
     - name: web
       port: 80
       target_port: 8081

- name: create http-source route
  openshift_v1_route:
   name: http-source
   namespace: '{{ namespace }}'
   labels:
     app: event-gateway
     service: http-source
   to_name: http-source
   spec_port_target_port: web
